### ISSUE TITLE
Installation of `atoMEC`

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/notebooks#1]
There are two ways for installing the `atoMEC` package: either within the `Pipfile` or manually by executing a cell in the notebooks.

The first approach requires to add the `atoMEC` dependency to the `Pipefile` like so

```toml
[packages]
atoMEC = {editable = true, ref = "develop", git = "https://github.com/atomec-project/atoMEC.git"}
```
the second approach requires to execute the following command inside a cell at the top of the notebook(s) (before doing the imports)

```sh
!pip install [-q] git+https://github.com/atomec-project/atoMEC.git@develop#egg=atoMEC
```
(the `-q` quiet flag may come in handy when executed inside a notebook).

Either way should work. Up to now, I am not sure which way would be more convenient. When `atoMEC` is mature and tagged, I would recommend the first approach, but as long as it is under heavy development I guess the latter approach is more suitable since it guarantees that one always got the latest development version of `atoMEC`. For the first approach a `pipenv update atoMEC` is necessary to update the local virtual environment to reflect the latest changes of `atoMEC` - if there are any.

**Comment by timcallow** [comment]
We chose the second approach for the current notebook and it seems to be working fine. Therefore I'm closing this issue.
